# Generated by Django 3.2.8 on 2021-11-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211105_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.TextField(help_text='Required and unique', unique=True, verbose_name='Type Name')),
                ('serviceability_disclaimer_title', models.TextField(blank=True, help_text='Required and unique', null=True, verbose_name='Serviceability Disclaimer Title')),
                ('serviceability_disclaimer_desc', models.TextField(blank=True, help_text='Required and unique', null=True, verbose_name='Serviceability Disclaimer Description')),
                ('is_active', models.BooleanField(default=True)),
                ('is_returnable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Product Type',
                'verbose_name_plural': 'Product Types',
            },
        ),
    ]
