# Generated by Django 3.2.8 on 2021-11-05 13:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_producttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetailsvalue',
            name='key',
        ),
        migrations.RemoveField(
            model_name='productdetailsvalue',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at',), 'verbose_name': 'Product=', 'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='regular_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
        migrations.AddField(
            model_name='product',
            name='base_colour',
            field=models.CharField(default='', help_text='Required', max_length=50, verbose_name='Colour'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='brand_name',
            field=models.CharField(default='', help_text='Required ', max_length=50, unique=True, verbose_name='Brand Display Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='colour1',
            field=models.CharField(default='', help_text='Required', max_length=50, verbose_name='Other Colour 1'),
        ),
        migrations.AddField(
            model_name='product',
            name='colour2',
            field=models.CharField(default='', help_text='Required', max_length=50, verbose_name='Other Colour 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.IntegerField(default=10, help_text='Required', validators=[django.core.validators.MinValueValidator(10)], verbose_name='Discounted Price in INR'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='display_name',
            field=models.CharField(default='', help_text='Required ', max_length=255, unique=True, verbose_name='Product Display Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='is_product_in_dataset',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_returnable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.URLField(default='', help_text='Required', verbose_name='Image link of the produc'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=10, help_text='Required', validators=[django.core.validators.MinValueValidator(10)], verbose_name='Price in INR'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='api.producttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='qty_avail',
            field=models.IntegerField(default=1, help_text='Required', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Amount of products'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='serviceability_disclaimer_desc',
            field=models.TextField(blank=True, help_text='Required and unique', null=True, verbose_name='Serviceability Disclaimer Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Html field allowed', verbose_name='Product Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(default='', max_length=255, verbose_name='Alternative text'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='serviceability_disclaimer_title',
            field=models.CharField(blank=True, help_text='Required and unique', max_length=255, null=True, verbose_name='Serviceability Disclaimer Title'),
        ),
        migrations.DeleteModel(
            name='ProductDetailsKey',
        ),
        migrations.DeleteModel(
            name='ProductDetailsValue',
        ),
    ]
