# Generated by Django 3.2.8 on 2021-11-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211105_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_returnable',
        ),
        migrations.RemoveField(
            model_name='product',
            name='serviceability_disclaimer_desc',
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default='', max_length=1, verbose_name='Select gender'),
            preserve_default=False,
        ),
    ]
