# Generated by Django 3.2.8 on 2021-11-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
