# Generated by Django 3.2.8 on 2021-11-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True),
        ),
    ]
