const ProductData = [
  {
    id: 23563,
    price: 2900,
    discounted_price: 2900,
    brand_name: 'Police',
    base_colour: 'Navy Blue',
    colour1: 'NA',
    colour2: 'NA',
    rating: 4,
    category: 36,
    product_type: 162,
    desc: '<span>The Pure London homme fragrance for men from police is for the conservatice yet suave male, respecting the past while fusing it effectively with the modern to create your own style. Symbolically, the pebble shaped flacon features the Union Jack. This fragrance has top notes of lavender, incense and ginger  a heart featuring warm notes of cardamom, amber and patchouli  and the base has cedar, vanilla and musk tones.<br><br>Quantity: 75 ml<br><br>Caution<br>Flammable<br>Keep away from sources of ignition<br>Keep away from children<br>Do not use near fire, flame or heat<br>Avoid spraying near the eyes</span>',
    created_at: 1461843608,
    gender: 'Men',
    display_name: 'Police Pure Men Perfume',
    image_link:
      'http://assets.myntassets.com/v1/images/style/properties/9644649259d14d9dc80418f100a60cf3_images.jpg',
  },
  {
    id: 55301,
    price: 350,
    discounted_price: 315,
    brand_name: 'Lakme',
    base_colour: 'Green',
    colour1: 'NA',
    colour2: 'NA',
    rating: 0,
    category: 265,
    product_type: 243,
    desc: 'Creamy colour<br /> With glitter<br /> Glides on easily',
    created_at: 1454664191,
    gender: 'Women',
    display_name: 'Lakme Shadow Artist Shimmer Stick',
    image_link:
      'http://assets.myntassets.com/v1/images/style/properties/Lakme-Shadow-Artist-Shimmer-Stick_3ec4633b3f3096011442ba801936883e_images.jpg',
  },
  {
    id: 57549,
    price: 395,
    discounted_price: 296,
    brand_name: 'Lotus Herbals',
    base_colour: 'Red',
    colour1: 'NA',
    colour2: 'NA',
    rating: 0,
    category: 263,
    product_type: 234,
    desc: 'Lip colour enriched with botanical extracts that hydrate and protect lips and lasts for hours, convenient twist up lipsticks with no separate cover',
    created_at: 1454666129,
    gender: 'Women',
    display_name: 'Lotus Herbals Floral Glam Apple Berry Lipstick 001',
    image_link:
      'http://assets.myntassets.com/v1/images/style/properties/Lotus-Herbals-Floral-Glam-Apple-Berry-Lipstick-001_dd29eb0f9101ab58b3cda481ee6badb5_images.jpg',
  },
  {
    id: 55132,
    price: 160,
    discounted_price: 144,
    brand_name: 'Lakme',
    base_colour: 'White',
    colour1: 'NA',
    colour2: 'NA',
    rating: 0,
    category: 264,
    product_type: 246,
    desc: "<b>WHAT IT IS?</b><br />A nail colour that coats your nails to perfection; giving them a vibrant and elegant look.<br /><br /><b>WHAT IT DOES?</b><ul><li>Comes with Color Lock Technology that ensures the color stays on your nails for long</li><li>The chip-resistant feature keeps the color intact</li><li>Strengthens nails</li></ul><b>FEATURES</b><ul><li>Contains resins with color lock technology</li><li>Strengthens nails with a long-lasting nail enamel</li><li>Chip resistant</li><li>New glitter shades that give your nails a silk sheen</li><li>Lakme True Wear Color Crush coats your nails to perfection, giving them a vibrant and elegant look</li><li>The Lakme Truewear nail color range will add sparkle to your everyday life</li></ul><b>ABOUT THE COLLECTION</b><br />Trendy shades on the go and for every mood, Lakme True Wear Color Crush nail enamel make the world a better place Long-lasting by nature and chip-resistant, Lakme True Wear Color Crush coats your nails to perfection, giving them a vibrant and elegant look. A color for all seasons and occasions, the shades are simply a must-have. It has color lock technology and is resin-based, making it a perfect choice.<br /><br /><b>ABOUT THE BRAND</b><br />Lakme is India's No.1 color cosmetics brand offering a wide range of high-end, world-class color cosmetics and skincare products. Lakme has a vast product range specially crafted by experts for the Indian skin. The brand has also been redefining fashion in India with Lakme Fashion Week, India's premier fashion event.",
    created_at: 1454670637,
    gender: 'Women',
    display_name: 'Lakme Truewear Color Crush 08 Nail Polish',
    image_link:
      'http://assets.myntassets.com/v1/images/style/properties/Lakme-Truewear-Color-Crush-Nail-Polish-08_eb894fc67edcb89112dd12ba7621a4b8_images.jpg',
  },
  {
    id: 32533,
    price: 849,
    discounted_price: 551,
    brand_name: 'Playboy',
    base_colour: 'Black',
    colour1: 'NA',
    colour2: 'NA',
    rating: 0,
    category: 36,
    product_type: 189,
    desc: '<p><strong></strong><strong>Style Note</strong><br />This Hollywood set from playboy is perfect as a gift or for a little self indulgence. <br /><br /><strong>Product Details</strong><br />Cologne and body spray set<br />Top notes are are mandarin and bergamot, along with aromatic accords of  thyme and elemi, the heart consists of calming lavender with jasmine,  rosewood and cedar with a base of vetiver, musk, amber, vanilla and  sandalwood<br /><br /><strong>Caution</strong><br />Do not use near fire, flame or heat<br />Avoid spraying in eyes<br /><strong><br />Size</strong><br />Cologne: 100 ml<br />Body Spray: 150 ml</p>',
    created_at: 1447444106,
    gender: 'Men',
    display_name: 'Playboy Men Hollywood Fragrance Gift Set',
    image_link:
      'http://assets.myntassets.com/assets/images/32533/2019/1/25/a67cbb37-a8d9-44ad-9515-b8f606b5c6d11548412852142-Playboy-Men-Hollywood-Fragrance-Gift-Set-8761548412852025-1.jpg',
  },
  {
    id: 46693,
    price: 750,
    discounted_price: 750,
    brand_name: 'Rasasi',
    base_colour: 'Blue',
    colour1: 'White',
    colour2: 'NA',
    rating: 0,
    category: 36,
    product_type: 162,
    desc: "<p><strong>Style Note</strong><br /> rasasi impresses and flatters your senses with their unique fragrances that last long and keep you smelling fresh. These are fragrances that will please the royals just as it would appeal to your more earthy senses. Each and every one of their perfumes are keepers. This perfume for women expresses sensual boldness evoking a youthful feeling.  <br /> <br /> <strong>Product Details</strong><br /> Rasasi Blue Lady is a women's perfume spray which has a flowery, woody and amber fragrance. The top notes are violet leaves, ylang - ylang, tuberose and orange blossom. The middle notes are peach, plum, narcissus and jasmine. Base notes are sandalwood, vetiver, vanilla, amber and musk. The perfume is bottled curvy blue flask with a golden collar while the clear cap resembles a women's hat. <br /> Comes with a free deo spray inside<br /> <br /> <strong>Size</strong><br /> 40 ml</p>",
    created_at: 1465971411,
    gender: 'Women',
    display_name: 'Rasasi Women Blue Lady Perfume',
    image_link:
      'http://assets.myntassets.com/v1/images/style/properties/e6de5f9b972651add14fd58b066e209a_images.jpg',
  },
  {
    id: 55226,
    price: 60,
    discounted_price: 54,
    brand_name: 'Lakme',
    base_colour: 'Black',
    colour1: 'NA',
    colour2: 'NA',
    rating: 0,
    category: 265,
    product_type: 269,
    desc: '<p>lakme kajal has camphor and castor oil which cools and soothes the eyes while helping the lashes to grow longer</p>',
    created_at: 1454674986,
    gender: 'Women',
    display_name: 'Lakme Kajal',
    image_link:
      'http://assets.myntassets.com/v1/images/style/properties/Lakme-Kajal_f3889855ced5d32eb69f42894428d147_images.jpg',
  },
  {
    id: 56385,
    price: 3030,
    discounted_price: 3030,
    brand_name: 'Estee Lauder',
    base_colour: 'Green',
    colour1: 'NA',
    colour2: 'NA',
    rating: 0,
    category: 36,
    product_type: 162,
    desc: '<span>estee lauder Youth &amp; ndash  Dew for women comes in a curvy glass flask with a bow detail in the middle<br> The top notes are rose, jonquil and lavender<br> The middle notes are jasmine, muguet and spices<br> The base notes are moss, vetiver and patchouli</span>',
    created_at: 1462357370,
    gender: 'Women',
    display_name: 'Estee Lauder Women Youth-Dew Perfume',
    image_link:
      'http://assets.myntassets.com/v1/images/style/properties/Estee-Lauder-Women-Youth-Dew-Perfume_1446627b71aa927cf9491a1389cd7674_images.jpg',
  },
  {
    id: 55208,
    price: 725,
    discounted_price: 652,
    brand_name: 'Lakme',
    base_colour: 'Brown',
    colour1: 'NA',
    colour2: 'NA',
    rating: 0,
    category: 263,
    product_type: 234,
    desc: 'Lakm&eacute;    Lip Love is enriched with SPF 16 which nourishes and protects your lips while hydrating them',
    created_at: 1454666123,
    gender: 'Women',
    display_name: 'Lakme Lip Love Aphrodite Blush Lipstick',
    image_link:
      'http://assets.myntassets.com/v1/images/style/properties/Lakme-Lip-Love-Aphrodite-Blush-Lipstick_61eb62f1c59261ada5bdc8f79860ed19_images.jpg',
  },
]

export default ProductData
