# Generated by Django 3.2.8 on 2021-11-05 19:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.TextField(help_text='Required and unique', unique=True, verbose_name='Category Name')),
                ('is_active', models.BooleanField(default=True)),
                ('is_returnable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(help_text='Required ', max_length=255, unique=True, verbose_name='Product Display Name')),
                ('brand_name', models.CharField(help_text='Required ', max_length=50, unique=True, verbose_name='Brand Display Name')),
                ('base_colour', models.CharField(help_text='Required', max_length=50, verbose_name='Colour')),
                ('colour1', models.CharField(default='', max_length=50, verbose_name='Other Colour 1')),
                ('colour2', models.CharField(default='', max_length=50, verbose_name='Other Colour 2')),
                ('price', models.IntegerField(help_text='Required', validators=[django.core.validators.MinValueValidator(10)], verbose_name='Price in INR')),
                ('discounted_price', models.IntegerField(validators=[django.core.validators.MinValueValidator(10)], verbose_name='Discounted Price in INR')),
                ('qty_avail', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='No of products')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1, verbose_name='Select gender')),
                ('description', models.TextField(help_text='Html field allowed', verbose_name='Product Description')),
                ('link', models.URLField(default='', help_text='Image link of the product', verbose_name='Link')),
                ('slug', models.SlugField(blank=True, help_text='Leave blank for default value', max_length=255, unique=True)),
                ('is_product_in_dataset', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='products.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type_name', models.TextField(help_text='Required and unique', unique=True, verbose_name='Type Name')),
                ('serviceability_disclaimer_title', models.CharField(blank=True, help_text='Required and unique', max_length=255, null=True, verbose_name='Serviceability Disclaimer Title')),
                ('serviceability_disclaimer_desc', models.TextField(blank=True, help_text='Required and unique', null=True, verbose_name='Serviceability Disclaimer Description')),
                ('is_active', models.BooleanField(default=True)),
                ('is_returnable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Product Type',
                'verbose_name_plural': 'Product Types',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='uploads/images/default.png', help_text='Upload a product image', upload_to='uploads/images/', verbose_name='Image')),
                ('alt_text', models.CharField(default='', max_length=255, verbose_name='Alternative text')),
                ('is_feature', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='products.producttype'),
        ),
    ]
