# Generated by Django 3.2.8 on 2021-11-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand_name',
            field=models.CharField(help_text='Required ', max_length=50, verbose_name='Brand Display Name'),
        ),
    ]
